---
name: Build musl-gcc

on:
  push:
    paths:
      - .github/workflows/build.yml
      - build.sh
      - config.mak
    branches:
      - main

  workflow_dispatch: null

jobs:
  build-musl-gcc:
    runs-on: ${{ matrix.runner }}
    container: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/builder:ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-latest-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.COMMIT_TOKEN }}

      - name: Build
        id: build
        shell: bash
        run: |
          set -ex

          git config user.name "bot"
          git config user.email "bot@noreply.mtdcy.top"
          git config --global --add safe.directory '*'

          make

          echo "tag=$(git describe --abbrev=0 --tags)" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: actions/gitea-release-action@v1
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
          tag_name: ${{ steps.build.outputs.tag }}
          name: ${{ steps.build.outputs.tag }}
          body_path: config.md
          append_body: false
          make_latest: true
          files: |-
            *.tar.xz
            *.log.gz
