---
name: Build musl-gcc

on:
  push:
    paths:
      - .github/workflows/build.yml
      - build.sh
    branches:
      - main

  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Which tag to build

env:
  tag: v0.9.11

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build
        id: build
        shell: bash
        run: |
          set -ex

          tag="${{ github.event.inputs.tag }}"
          [ -n "$tag" ] || tag=${{ env.tag }}

          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "target=$(uname -m)-unknown-linux-musl" >> "$GITHUB_OUTPUT"

          TAG=$tag ./build.sh

      - name: Release
        uses: actions/gitea-release-action@v1
        with:
          tag_name: ${{ steps.build.outputs.tag }}
          name: ${{ steps.build.outputs.target }}
          body: ${{ steps.build.outputs.target }}
          append_body: false
          make_latest: true
          files: |-
            *.tar.xz
